{{ if .Values.serviceAccount.enabled -}}
{{ $serviceAccounts := fromYaml .Values.serviceAccount.names -}}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $serviceAccounts.k8s_account }}
  annotations:
    argocd.argoproj.io/sync-wave: "20"
    {{- if (hasKey $serviceAccounts "gcp_account") }}
    iam.gke.io/gcp-service-account: {{ $serviceAccounts.gcp_account }}
    {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $serviceAccounts.k8s_account }}
  annotations:
    argocd.argoproj.io/sync-wave: "20"
rules: {{ toYaml .Values.serviceAccount.rules | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $serviceAccounts.k8s_account }}
  annotations:
    argocd.argoproj.io/sync-wave: "20"
subjects:
- kind: ServiceAccount
  name: {{ $serviceAccounts.k8s_account }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ $serviceAccounts.k8s_account }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
