apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

buildMetadata: [originAnnotations]
namespace: farm


#If you need to refer to a key with ~ or / in its name, you must escape the characters with ~0 and ~1 respectively. For example, to get "baz" from { "foo/bar~": "baz" } you’d use the pointer /foo~1bar~0.
patches:
  - target:
      version: v1
      kind: Deployment
      name: farm
    patch: |-
      - op: replace
        path: /metadata/labels/tags.datadoghq.com~1env
        value: stg
      - op: replace
        path: /spec/template/metadata/labels/tags.datadoghq.com~1env
        value: stg


resources:
  - ../../../base
