apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- deployment.yaml
- rolebinding.yaml
- serviceaccount.yaml


commonLabels:
  app.kubernetes.io/name: farm

transformers:
  - datadogtags.yaml

