apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: farm-argo-cluster-role
  namespace: farm
subjects:
- kind: ServiceAccount
  name: farm
roleRef:
  kind: ClusterRole #this must be Role or ClusterRole
  name: argo-cluster-role # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: farm-view
  namespace: farm
subjects:
  - kind: ServiceAccount
    name: farm
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
