apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

buildMetadata: [originAnnotations]
namespace: farm

resources:
  - ../../../environments/stg


patches:
  - target:
      version: v1
      kind: Deployment
      name: farm
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: eddie
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: FARM_AIRFLOW_HOST
          value: "188ad5899b0d9e90a86eb912fa1b4736ecb-dot-europe-west4.composer.googleusercontent.com"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: FARM_ARGO_NAMESPACE
          value: "eddie"
